<a href="https://colab.research.google.com/github/vkjadon/sklearn/blob/main/01sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
from sklearn import linear_model

In [ ]:
#X=np.array([[100],[150],[200],[250],[500], [1000],[2500],[5000]])
X=np.array([[100, 1],[150, 1],[200, 2],[250, 2],[500, 3], [1000, 4],[2500, 4],[5000, 5]])
y=np.array([20,28, 39, 51, 75, 130, 210, 400])

In [ ]:
print(X)

[[ 100    1]
 [ 150    1]
 [ 200    2]
 [ 250    2]
 [ 500    3]
 [1000    4]
 [2500    4]
 [5000    5]]


In [ ]:
print(y)

[ 20  28  39  51  75 130 210 400]


In [ ]:
print(X.shape, type(X), y.shape, type(y))
# print(X, y)

(8, 2) <class 'numpy.ndarray'> (8,) <class 'numpy.ndarray'>


In [ ]:
# Create a Logistic Regression Object, perform Logistic Regression
lr = linear_model.LinearRegression()
lr.fit(X, y)
print(lr.coef_)
print(lr.intercept_)

[ 0.06429476 14.80232017]
0.46122252435984024


## Importing Dataset

[Toy SciKit-Learn Dataset](https://scikit-learn.org/stable/datasets/toy_dataset.html)

In [12]:
from sklearn import datasets

In [ ]:
dir(datasets)

 [Syntax of load dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_diabetes.html)

In [13]:
# Load the diabetes dataset
diabetes = datasets.load_diabetes()
diabetes_X, y = datasets.load_diabetes(return_X_y=True)

In [14]:
print(diabetes)

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]]), 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
  

In [ ]:
print(diabetes.feature_names)

In [ ]:
print(diabetes.target)

In [ ]:
print(diabetes.DESCR)

In [15]:
print(diabetes_X.shape)
print(type(diabetes_X))
print(y.shape)

(442, 10)
<class 'numpy.ndarray'>
(442,)


In [ ]:
# Using the jth feature
j=[1,2,3,4]
X = diabetes_X[:, j] # All Rows of jth column
X=X.reshape(diabetes_X.shape[0],len(j)) # To restrict to only desired columns list `j`
print(X.shape)
# print(type(X))
print(X)


(442, 4)
[[ 0.05068012  0.06169621  0.02187235 -0.0442235 ]
 [-0.04464164 -0.05147406 -0.02632783 -0.00844872]
 [ 0.05068012  0.04445121 -0.00567061 -0.04559945]
 ...
 [ 0.05068012 -0.01590626  0.01728186 -0.03734373]
 [-0.04464164  0.03906215  0.00121513  0.01631843]
 [-0.04464164 -0.0730303  -0.08141377  0.08374012]]


In [ ]:
# Using all the features
X = diabetes_X
print(X.shape)
#print(type(X))
#print(X)

(442, 10)


In [ ]:
print(y)

In [ ]:
# Create linear regression object
lr = linear_model.LinearRegression()

# Train the model using the training sets
lr.fit(X, y)

# The coefficients
w_skl=lr.coef_.reshape(X.shape[1],1)
b_skl=lr.intercept_
print("Coefficients: \n", w_skl)
print("Intercept: \n", b_skl)

In [ ]:
import sklearn
dir(sklearn)

https://scikit-learn.org/stable/datasets.html#datasets

In [3]:
from sklearn.datasets import fetch_openml

In [19]:
X, y = fetch_openml("titanic", version=9, as_frame=True, return_X_y=True)

In [ ]:
print(X)

https://scikit-learn.org/stable/datasets/loading_other_datasets.html

In [24]:
from sklearn.datasets import fetch_openml
mice = fetch_openml(name='miceprotein', version=4)

In [27]:
print(mice.data.shape)
print(mice.target.shape)

(1080, 77)
(1080,)


In [28]:
print(mice.DESCR)

**Author**: Clara Higuera, Katheleen J. Gardiner, Krzysztof J. Cios  
**Source**: [UCI](https://archive.ics.uci.edu/ml/datasets/Mice+Protein+Expression) - 2015   
**Please cite**: Higuera C, Gardiner KJ, Cios KJ (2015) Self-Organizing Feature Maps Identify Proteins Critical to Learning in a Mouse Model of Down Syndrome. PLoS ONE 10(6): e0129126.

Expression levels of 77 proteins measured in the cerebral cortex of 8 classes of control and Down syndrome mice exposed to context fear conditioning, a task used to assess associative learning.

The data set consists of the expression levels of 77 proteins/protein modifications that produced detectable signals in the nuclear fraction of cortex. There are 38 control mice and 34 trisomic mice (Down syndrome), for a total of 72 mice. In the experiments, 15 measurements were registered of each protein per sample/mouse. Therefore, for control mice, there are 38x15, or 570 measurements, and for trisomic mice, there are 34x15, or 510 measurements. Th

In [ ]:
print(mice.details)

In [38]:
iris = fetch_openml(name="iris")
print(iris.details['version'])
print(iris.details['id'])

1
61


In [37]:
iris_61 = fetch_openml(data_id=61)
print(iris_61.details['version'])
print(iris_61.details['id'])

1
61


In [40]:
iris_969 = fetch_openml(data_id=969)
print(iris_969.details['version'])
print(iris_969.details['id'])

3
969
