<a href="https://colab.research.google.com/github/vkjadon/sklearn/blob/main/01sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [9]:
from sklearn import linear_model
X=np.array([[100],[150],[200],[250],[500], [1000],[2500],[5000]])
#X=np.array([[100, 1],[150, 1],[200, 2],[250, 2],[500, 3], [1000, 4],[2500, 4],[5000, 5]])
y=np.array([20,28, 39, 51, 75, 130, 210, 400])

In [7]:
print(X.shape, type(X), y.shape, type(y))
# print(X, y)

(8, 2) <class 'numpy.ndarray'> (8,) <class 'numpy.ndarray'>


In [8]:
# Create a Logistic Regression Object, perform Logistic Regression
lr = linear_model.LinearRegression()
lr.fit(X, y)
print(lr.coef_)
print(lr.intercept_)

[ 0.06429476 14.80232017]
0.46122252435984024


## Importing Dataset

[Toy SciKit-Learn Dataset](https://scikit-learn.org/stable/datasets/toy_dataset.html)

In [10]:
from sklearn import datasets

In [ ]:
dir(datasets)

 [Syntax of load dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_diabetes.html)

In [13]:
# Load the diabetes dataset
diabetes_X, y = datasets.load_diabetes(return_X_y=True)

In [14]:
print(diabetes_X.shape)
print(type(diabetes_X))
print(y.shape)

(442, 10)
<class 'numpy.ndarray'>
(442,)


In [20]:
# Using the jth feature
j=[1,2,3,4]
X = diabetes_X[:, j] # All Rows of jth column
X=X.reshape(diabetes_X.shape[0],len(j)) # To restrict to only desired columns list `j`
print(X.shape)
# print(type(X))
print(X)


(442, 4)
[[ 0.05068012  0.06169621  0.02187235 -0.0442235 ]
 [-0.04464164 -0.05147406 -0.02632783 -0.00844872]
 [ 0.05068012  0.04445121 -0.00567061 -0.04559945]
 ...
 [ 0.05068012 -0.01590626  0.01728186 -0.03734373]
 [-0.04464164  0.03906215  0.00121513  0.01631843]
 [-0.04464164 -0.0730303  -0.08141377  0.08374012]]


In [21]:
# Using all the features
X = diabetes_X
print(X.shape)
#print(type(X))
#print(X)

(442, 10)


In [22]:
# Create linear regression object
lr = linear_model.LinearRegression()

# Train the model using the training sets
lr.fit(X, y)

# The coefficients
w_skl=lr.coef_.reshape(X.shape[1],1)
b_skl=lr.intercept_
print("Coefficients: \n", w_skl)
print("Intercept: \n", b_skl)

Coefficients: 
 [[ -10.01219782]
 [-239.81908937]
 [ 519.83978679]
 [ 324.39042769]
 [-792.18416163]
 [ 476.74583782]
 [ 101.04457032]
 [ 177.06417623]
 [ 751.27932109]
 [  67.62538639]]
Intercept: 
 152.1334841628965
